spring.application.name=quizz
# Включаем H2 консоль (по адресу /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Подключение к базе H2 (в памяти)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Автоматическое создание таблиц
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.sql.init.platform=h2

# JWT настройки
jwt.secret=mySuperSecretKeyForJwtTokensInQuizzApplication123456789
jwt.expiration=86400000

# Настройки почты (заменить на свои)
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}lait_34@mail.ru
spring.mail.password=${MAIL_PASSWORD}meq4jYudrFR5kQWhEBkL
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# Настройки кеша OTP
otp.cache.expire-after-write=300

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
logging.level.org.springframework.mail.javamail=TRACE