spring.application.name=quizz
# Включаем H2 консоль (по адресу /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Подключение к базе H2 (в памяти)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Автоматическое создание таблиц
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
spring.sql.init.platform=h2