name: Deploy

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: self-hosted  # используем self-hosted runner
    env:
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop and remove existing containers
        run: |
          docker-compose down || true
          docker system prune -f || true  # Удаляет неиспользуемые данные (опционально)

      - name: Build Docker images with docker-compose
        run: docker-compose build --no-cache

      - name: Deploy application with docker-compose
        run: docker-compose up -d --force-recreate
